# Generated by Django 4.1.3 on 2022-12-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
